#!/bin/sh -e

TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/server-ubuntu18-cv

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh ./build/couchbuilder_start.sh
cp -a ../../util/healthcheck.sh build
cp ../../util/hooks/buildx.sh ./build/

. ../versions


if [ "$1" = "--publish" ]
then
  ACTION=--push
else
  ACTION=--load
fi

docker buildx build --pull ${ACTION} \
  --platform linux/amd64 \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg VALGRIND_VERSION=${VALGRIND_VERSION} \
  --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
  --build-arg JYTHON_VERSION=${JYTHON_VERSION} \
  .
