#!/bin/bash -e

GCC_VER=7.3.0
IMAGE=couchbasebuild/amzn-2-gcc

ARCH=$(uname -m)
if [ "$ARCH" = "x86_64" ]
then
  echo "Error: This should only be used to build the aarch64 placeholder image, it should never be built on x86 to avoid the risk of accidentally replacing the legitimate x86_64 gcc:7.3.0 build"
  exit 1
fi

docker build \
    --build-arg GCC_VER=${GCC_VER} \
    -t ${IMAGE}:${GCC_VER}-${ARCH} .

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${GCC_VER}-${ARCH}
fi
