#!/bin/bash

# In order to update configs without needing to change datestamps all the
# time, easiest just to blow away the stack and re-create.
docker --host mega4.build.couchbase.com stack rm profiledata
sleep 5
docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c profiledata.yaml profiledata
