#!/bin/bash -e

export TAG=$(date '+%Y-%m-%d')
export PRODUCTION_TAG=2025-10-17
export DATADIR=/opt/pathdiff/data
export DOCKER_SOCKET=/var/run/docker.sock

case "$1" in
    "--dev")
        export DATADIR=/tmp/pathdiffdb
        export TAG=dev
        # We do a bare build for dev - this applies the .override.yml
        # automatically
        mkdir -p ${DATADIR}
        docker compose build
        docker compose up --remove-orphans
        ;;
    "--publish")
        # Specifying files, override isn't used
        docker compose -f docker-compose.yml build
        docker compose push
        ;;
    "--deploy")
        export TAG=${PRODUCTION_TAG}
        docker -H mega4.build.couchbase.com stack deploy --with-registry-auth -c docker-compose.yml pathdiff
        ;;
esac
