#!/bin/sh -e

TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/server-ubuntu18-docker-cv

cp ../../util/couchbuilder_transition_start.sh ./couchbuilder_start.sh

docker build \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg DOCKER_VERSION=20.10.6 \
  -t ${IMAGE}:${TAG} \
  -t ${IMAGE}:latest \
  .

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
