#!/bin/sh -e

TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/server-ubuntu18-docker-cv

mkdir -p build
cp ../../util/couchbuilder_transition_start.sh ./build/couchbuilder_start.sh
cp ../../util/healthcheck.sh ./build/
cp ../../util/hooks/buildx.sh ./build/

docker build \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg DOCKER_VERSION=20.10.6 \
  -t ${IMAGE}:${TAG} \
  -t ${IMAGE}:latest \
  .

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
