---
- name: Install required packages for couchbase-cloud self-hosted runner VM
  block:
    - name: Add additional packages
      apt:
        name:
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - docker-compose-plugin
          - gnupg
          - gnupg2
          - jq
          - lsb-release
          - pass
          - python3-pip
          - unzip
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Add docker-credential-pass
      shell: |-
        cd /tmp

        GPG_TEMPLATE=$(mktemp gpg_template.XXXXXX)
        cat > $GPG_TEMPLATE <<-EOF
          Key-Type: RSA
          Key-Length: 2048
          Name-Real: GitHubActions
          Expire-Date: 0
          %no-protection
          %no-ask-passphrase
          %commit
        EOF
        gpg2 --batch --gen-key "$GPG_TEMPLATE"
        FINGERPRINT_STRING=$(gpg2 --list-keys --with-fingerprint --with-colons GitHubActions | grep fpr)
        arrFINGERPRINT=(${FINGERPRINT_STRING//:/ })
        FINGERPRINT=${arrFINGERPRINT[-1]}
        pass init $FINGERPRINT
        rm $GPG_TEMPLATE

        RELEASE_VERSION=$(curl -Ls --fail --retry 3 -o /dev/null -w %{url_effective} 'https://github.com/docker/docker-credential-helpers/releases/latest' | sed 's:.*/::')
        curl -L -o "docker-credential-pass" "https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/docker-credential-pass-${RELEASE_VERSION}.linux-amd64"
        chmod +x "./docker-credential-pass"
        mv "./docker-credential-pass" "/usr/local/bin"
        /usr/local/bin/docker-credential-pass version
      args:
        executable: /usr/bin/bash
      become: true
      tags: docker

    - name: Add Azure repo
      shell: |
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` \
        signed-by=/etc/apt/keyrings/microsoft.gpg]  \
        https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list

    - name: Add Azure cli
      apt:
        name:
          - azure-cli
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Add gcloud repo
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
        https://packages.cloud.google.com/apt cloud-sdk main" |
        sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |
        sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

    - name: Add gcloud cli
      apt:
        name:
          - google-cloud-cli
        state: present
        update_cache: yes
      become: true
      tags: pkgs
