#!/bin/bash -e

TAG=$(date "+%Y%m%d")
IMAGE="couchbasebuild/ubuntu-1604-recreate-build-manifest"

docker build --no-cache -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
