#!/bin/sh -e

TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/migrate-vm

if [ -e migrate-vm ]; then
  (cd migrate-vm; git pull)
else
  git clone git://github.com/djamps/migrate-vm
fi

docker build -t $IMAGE:$TAG .
docker tag $IMAGE:$TAG $IMAGE:latest
if [ "$1" = "--publish" ]
then
  docker push $IMAGE:$TAG
  docker push $IMAGE:latest
fi
