#!/bin/bash -e

GCC_VER=${GCC_VER:-12.2.0}
IMAGE=couchbasebuild/amzn-2-gcc

ARCH=$(uname -m)

if [ "$1" = "--publish" ]
then
  ACTION=--push
  PLATFORMS="--platform linux/amd64,linux/arm64"
else
  ACTION=--load
fi

docker buildx build ${ACTION} \
    ${PLATFORMS} \
    --build-arg GCC_VER=${GCC_VER} \
    -t ${IMAGE}:${GCC_VER} .
