#!/bin/sh -ex

export GCC_VER=${GCC_VER:-13.2.0}
export BINUTILS_VER=${BINUTILS_VER:-2.41}
export DOCKER_BUILDKIT=1
DATE=$(date +%Y%m%d)

IMAGE_NAME=couchbasebuild/single-gcc

if [ "$1" = "--publish" ]
then
  BUILDER=buildx
  PLATFORMS="--platform linux/amd64,linux/arm64"
  PUSH=--push
fi

docker ${BUILDER} build \
  -f Dockerfile \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --build-arg GCC_VER=${GCC_VER} \
  --build-arg BINUTILS_VER=${BINUTILS_VER} \
  ${PLATFORMS} \
  --pull ${PUSH} \
  --tag ${IMAGE_NAME}:${GCC_VER}-${DATE} \
  .
