version: '3.8'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy -c server-jenkins-buildslaves.yml serverbuild
# All services, networks, etc. will then get an "serverbuild_" prefix,
# eg. "serverbuild_centos6"

# Default slave configuration. This is written using a YAML anchor so
# it can be substituted into all the slave declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd

x-default-jenkins-slave: &default-jenkins-slave
  deploy:
    replicas: 2
    update_config:
      parallelism: 1000
  networks:
    - jenkins

  secrets:
    - source: jenkins_master_username
    - source: jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync

x-default-jenkins-slave-environment:
 - &default-jenkins-slave-environment-master "JENKINS_MASTER=http://mega1.build.couchbase.com:8082/"

x-node-class:
 - &node-class "NODE_CLASS=build"

x-node-product:
 - &node-product "NODE_PRODUCT=couchbase-server"

services:

  amzn2:
    image: couchbasebuild/server-amzn2-build:20200729
    environment:
      - "JENKINS_SLAVE_NAME=server-amzn2"
      - "JENKINS_SLAVE_LABELS=server amzn2 alice mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  centos6:
    image: couchbasebuild/server-centos6-build:20200615
    environment:
      - "JENKINS_SLAVE_NAME=server-centos6"
      - "JENKINS_SLAVE_LABELS=server centos6 vulcan alice mad-hatter master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
      - "JAVA_OPTS=-Djava.util.logging.config.file=/swarm-logging.properties"
    <<: *default-jenkins-slave
    deploy:
      replicas: 1

  centos7:
    image: couchbasebuild/server-centos7-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-centos7"
      - "JENKINS_SLAVE_LABELS=server centos7 vulcan alice mad-hatter cheshire-cat master magma-preview"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave
    deploy:
      replicas: 3

  centos8:
    image: couchbasebuild/server-centos8-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-centos8"
      - "JENKINS_SLAVE_LABELS=server centos8 mad-hatter cheshire-cat master magma-preview"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave
    deploy:
      replicas: 3

  debian8-alice:
    image: couchbasebuild/server-debian8-alice-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-debian8-alice"
      - "JENKINS_SLAVE_LABELS=server debian8 vulcan alice"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave
    deploy:
      replicas: 1

  debian8:
    image: couchbasebuild/server-debian8-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-debian8"
      - "JENKINS_SLAVE_LABELS=server debian8 mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  debian9:
    image: couchbasebuild/server-debian9-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-debian9"
      - "JENKINS_SLAVE_LABELS=server debian9 vulcan alice mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  debian10:
    image: couchbasebuild/server-debian10-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-debian10"
      - "JENKINS_SLAVE_LABELS=server debian10 mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  rhel8:
    image: build-docker.couchbase.com/couchbasebuild/server-rhel8-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-rhel8"
      - "JENKINS_SLAVE_LABELS=server rhel8 alice"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  suse11:
    image: couchbasebuild/server-suse11-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-suse11"
      - "JENKINS_SLAVE_LABELS=server suse11 vulcan alice mad-hatter master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave
    deploy:
      replicas: 1

  suse15:
    image: couchbasebuild/server-suse15-build:20200729
    environment:
      - "JENKINS_SLAVE_NAME=server-suse15"
      - "JENKINS_SLAVE_LABELS=server suse15 mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  ubuntu14:
    image: couchbasebuild/server-ubuntu14-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu14"
      - "JENKINS_SLAVE_LABELS=server ubuntu14.04 ubuntu14 vulcan alice"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave
    deploy:
      replicas: 1

  ubuntu16:
    image: couchbasebuild/server-ubuntu16-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu16"
      - "JENKINS_SLAVE_LABELS=server ubuntu16.04 ubuntu16 vulcan alice mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  ubuntu18:
    image: couchbasebuild/server-ubuntu18-build:20200424
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu18"
      - "JENKINS_SLAVE_LABELS=server ubuntu18.04 ubuntu18.04-windowscrosscompile ubuntu18 alice mad-hatter cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  ubuntu20:
    image: couchbasebuild/server-ubuntu20-build:20200729
    init: true
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu20"
      - "JENKINS_SLAVE_LABELS=server ubuntu20.04 ubuntu20 cheshire-cat master"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave

  clamav:
    image: couchbasebuild/clamav-slave:20200424
    environment:
      - "JENKINS_SLAVE_NAME=clamav"
      - "JENKINS_SLAVE_LABELS=clamav"
      - *default-jenkins-slave-environment-master
      - *node-class
      - *node-product
    <<: *default-jenkins-slave
    deploy:
      replicas: 1

secrets:
  jenkins_master_username:
    external: true
  jenkins_master_password:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true

networks:
  jenkins:
