# Add homebrew and localbin to PATH
# homebrew is installed under /usr/local on x86_64
# under /opt/homebrew on M1
if [ -d "/opt/homebrew" ]; then
  export homebrew_dir=/opt/homebrew
  export PATH=$homebrew_dir/bin:$homebrew_dir/opt/python/libexec/bin:/usr/local/bin:$PATH
else
  export homebrew_dir=/usr/local
  export PATH=$homebrew_dir/bin:$homebrew_dir/opt/python/libexec/bin:$PATH
fi

# Make Homebrew’s completions available in zsh
# When getting “zsh compinit: insecure directories”, enable the chmod below.
# chmod -R go-w "$(brew --prefix)/share"
if type brew &>/dev/null; then FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH && autoload -Uz compinit && compinit; fi

# Add ruby to PATH
gem_paths=$(gem env | grep "INSTALLATION DIRECTORY" | sed 's/.*: //g'  | sed 's/$/\/bin/g' | paste -sd ":" -)
export PATH="${gem_paths}:$PATH"

# Ensure LANG can handle UTF-8 filenames
export LANG=en_US.UTF-8
