#!/bin/sh -e

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/ansible-agent

cp ../../util/couchbuilder_transition_start.sh ./couchbuilder_start.sh

docker build -t ${IMAGE}:$TAG .
docker tag ${IMAGE}:$TAG ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
