variable "prefix" {}
variable "vpc_id" {}
variable "private_subnets_cidr_blocks" {}
variable "private_subnets" {}
variable "ecs_execution_role" {}
variable "ecs_cluster" {}
variable "hostname" {}
variable "subdomain" {}
variable "domain" {}
variable "image" {}
variable "region" {}
variable "memory" {}
variable "cpu" {}
variable "dns_namespace" {}
variable "context" {}
variable "stopped" {}
variable "ecs_iam_role" {}
