#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/litec-the-ark

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

if [ "$1" = "--publish" ]
then
  ACTION="--push"
else
  ACTION="--load"
fi

docker buildx build --platform linux/amd64 --pull ${ACTION} \
    --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
    -t ${IMAGE}:${TAG} \
    -t ${IMAGE}:latest \
    .
