version: '3.8'

# Suggested deployment command:
#  docker --host 172.23.112.24 stack deploy --with-registry-auth -c cv-jenkins-agents.yml cv
# All services, networks, etc. will then get an "cv_" prefix,
# eg. "cv_ubuntu18_large"

# Default agent configuration. This is written using a YAML anchor so
# it can be substituted into all the agent declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-agent: &default-jenkins-agent
  networks:
    - jenkins
  sysctls:
    net.ipv6.conf.lo.disable_ipv6: 0

  configs:
    - source: jenkins_master_username
      target: /run/secrets/jenkins_master_username
      mode: 0444
  secrets:
    - source: cv_jenkins_ns-buildbot_api_key.20220510
      target: /run/secrets/jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync
    - source: dockerhub_nsbuildbot_password
      target: /tmp/dockerhub_nsbuildbot_password
  cap_add:
    - ALL
  stop_grace_period: 60m

services:

  zz-lightweight:
    image: couchbasebuild/zz-lightweight:20220708
    environment:
      - "JENKINS_SLAVE_NAME=cv-zz-lightweight"
      - "JENKINS_SLAVE_LABELS=zz-lightweight"
      - "JENKINS_SLAVE_EXECUTORS=10"
      - "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent

  # Placeholder service for aarch64
  # Note: this should always have zero replicas. Its presence here is
  # required to allow EC2 instances to discover the correct image.
  amzn2_aarch64:
    image: couchbasebuild/server-amzn2-build:20221205
    deploy:
      replicas: 0

  ubuntu18_docker:
    image: couchbasebuild/server-ubuntu18-cv:20230524
    environment:
      - "JENKINS_SLAVE_NAME=cv-ubuntu18-docker"
      - "JENKINS_SLAVE_LABELS=u18-docker-slave {{.Node.Hostname}} vulcan 6.5.0 6.5.1 6.5.2 6.6.0 7.0.0 mad-hatter cheshire-cat neo master ubuntu-18.04 small docker"
      - "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "PARALLELISM=3"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    <<: *default-jenkins-agent
    deploy:
      resources:
        reservations:
          # Docker nodes have 16GB RAM
          memory: 12G
      placement:
        constraints:
          - "node.labels.cvtype==docker"
        max_replicas_per_node: 1
      replicas: 2
      update_config:
        parallelism: 100
        delay: 0s

  ubuntu18_small:
    image: couchbasebuild/server-ubuntu18-cv:20230524
    environment:
      - "JENKINS_SLAVE_NAME=cv-ubuntu18-small"
      - "JENKINS_SLAVE_LABELS=u18-docker-slave {{.Node.Hostname}} vulcan 6.5.0 6.5.1 6.5.2 6.6.0 7.0.0 mad-hatter cheshire-cat neo ubuntu-18.04 small"
      - "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "PARALLELISM=3"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent
    deploy:
      resources:
        reservations:
          # Small nodes have 16GB RAM
          memory: 12G
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18-small"
        max_replicas_per_node: 1
      replicas: 1
      update_config:
        parallelism: 100
        delay: 0s

  ubuntu18_large:
    image: couchbasebuild/server-ubuntu18-cv:20230524
    environment:
      - "JENKINS_SLAVE_NAME=cv-ubuntu18-large"
      - "JENKINS_SLAVE_LABELS=u18-docker-slave {{.Node.Hostname}} vulcan 6.5.0 6.5.1 6.5.2 6.6.0 7.0.0 mad-hatter cheshire-cat neo ubuntu-18.04 large"
      - "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "PARALLELISM=16"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent
    deploy:
      resources:
        reservations:
          # Large nodes have 24GB RAM
          memory: 20G
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18-large"
        max_replicas_per_node: 1
      replicas: 1
      update_config:
        parallelism: 1000
        delay: 0s

  linux_small:
    image: couchbasebuild/server-linux-cv:20240129
    environment:
      - "JENKINS_SLAVE_NAME=cv-linux-small"
      - "JENKINS_SLAVE_LABELS={{.Node.Hostname}} master neo trinity cypher morpheus linux small"
      - "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "PARALLELISM=3"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent
    deploy:
      resources:
        reservations:
          # Small nodes have 16GB RAM
          memory: 12G
      placement:
        constraints:
          - "node.labels.cvtype==linux-small"
        max_replicas_per_node: 1
      replicas: 9
      update_config:
        parallelism: 100
        delay: 0s

  linux_large:
    image: couchbasebuild/server-linux-cv:20240129
    environment:
      - "JENKINS_SLAVE_NAME=cv-linux-large"
      - "JENKINS_SLAVE_LABELS={{.Node.Hostname}} master neo trinity cypher morpheus linux large"
      - "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "PARALLELISM=16"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent
    deploy:
      resources:
        reservations:
          # Large nodes have 24GB RAM
          memory: 20G
      placement:
        constraints:
          - "node.labels.cvtype==linux-large"
        max_replicas_per_node: 1
      replicas: 20
      update_config:
        parallelism: 1000
        delay: 0s

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

secrets:
  cv_jenkins_ns-buildbot_api_key.20220510:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true
  dockerhub_nsbuildbot_password:
    external: true

networks:
  jenkins:
    attachable: true
