version: '3.5'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c cv-jenkins.yaml cv
# All services, networks, etc. will then get an "cv_" prefix,
# eg. "cv_jenkins"

services:

  # cv.jenkins.couchbase.com
  jenkins:
    image: jenkins/jenkins:2.528.1
    deploy:
      resources:
        limits:
          memory: 7G
        reservations:
          memory: 7G
      placement:
        constraints:
          - node.labels.role==megajenkins
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"
        - "traefik.http.routers.cv_jenkins.rule=Host(`cv.jenkins.couchbase.com`)"
        - "traefik.http.services.cv_jenkins.loadbalancer.server.port=8080"
    ports:
      - "8480:8080"
      - "50002:50002"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/couchbase/cv-jenkins-home
        target: /var/jenkins_home
    networks:
      - jenkins
      - traefik_reverse-proxy

# See http://www.technowise.in/2016/10/fix-no-valid-crumb-was-included-in.html
# and https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Nginx
# for the reason behind -Dhudson.security.csrf.requestfield .
# See https://stackoverflow.com/a/39965700/1425601 and
# https://www.jenkins.io/doc/book/managing/system-properties/ for information
# about hudson.TcpSlaveAgentListener.hostName .
    environment:
      JAVA_OPTS: >-
          -Dhudson.model.ParametersAction.keepUndefinedParameters=true
          -Dhudson.security.csrf.requestfield=Jenkins-Crumb
          -Dhudson.TcpSlaveAgentListener.hostName=mega4.build.couchbase.com

networks:
  jenkins:
  traefik_reverse-proxy:
    external: true
