#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/litec-the-ark-3X

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

docker build --pull -t ${IMAGE}:$TAG .
docker tag ${IMAGE}:$TAG ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  set -x
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
