#!/bin/sh -e

if [ "${VERSION}" == "" ]; then
  echo "Usage: VERSION=3.14.3 ./go [--publish]"
  exit 1
fi

IMAGE=couchbasebuild/gerrit
mkdir -p build

for arg in "$@"; do
  case "${arg}" in
    --publish)
      PUBLISH=--push
      ;;
    *)
      echo "Invalid flag: ${arg}"
      exit 1
      ;;
  esac
done

docker buildx build ${PUBLISH} \
  --platform linux/amd64 \
  --tag ${IMAGE}:${VERSION} \
  --build-arg GERRIT_VER=${VERSION} \
  .
