version: '3.5'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c python-buildslaves.yml python
# All services, networks, etc. will then get an "python_" prefix,
# eg. "python_centos6"

# Default slave configuration. This is written using a YAML anchor so
# it can be substituted into all the slave declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-slave: &default-jenkins-slave
  deploy:
    placement:
      constraints:
        - node.labels.role==build
    replicas: 1
  configs:
    - source: couchbase_ssh_config_20191203
      target: /home/couchbase/.ssh/config
      uid: '1000'
      mode: 0400

  secrets:
    - source: jenkins_master_username
    - source: jenkins_master_password.20210721
      target: /run/secrets/jenkins_master_password
    - source: id_cb-robot_20191031
      target: /home/couchbase/.ssh/id_cb-robot
      uid: '1000'
      mode: 0400

x-default-jenkins-slave-environment:
 - &default-jenkins-slave-environment-master "JENKINS_MASTER=http://mega1.build.couchbase.com:8082/"

services:

  alpine:
    image: couchbasebuild/python-alpine-build:20211101
    environment:
      - "JENKINS_SLAVE_NAME=python-alpine"
      - "JENKINS_SLAVE_LABELS=alpine python3 x86_64"
      - *default-jenkins-slave-environment-master
      - "JAVA_OPTS=-Djava.util.logging.config.file=/swarm-logging.properties"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=couchbase-server"
    <<: *default-jenkins-slave

  centos6:
    image: couchbasebuild/python-centos6-build:20210917
    environment:
      - "JENKINS_SLAVE_NAME=python-centos6"
      - "JENKINS_SLAVE_LABELS=linux python3 x86_64"
      - *default-jenkins-slave-environment-master
      - "JAVA_OPTS=-Djava.util.logging.config.file=/swarm-logging.properties"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=couchbase-server"
    <<: *default-jenkins-slave

configs:
  couchbase_ssh_config_20191203:
    file: conf/couchbase_ssh_config

secrets:
  jenkins_master_username:
    external: true
  jenkins_master_password.20210721:
    external: true
  id_cb-robot_20191031:
    external: true
