#!/bin/sh

# Bump this when rebuilding with changes
TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/server-ubuntu16-cv

docker build --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
