#!/bin/sh -e

GCC_VER=11.2.0

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/centos-73-litecore-build

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

docker build \
  --build-arg GCC_VER=${GCC_VER} \
  -t ${IMAGE}:$TAG -t ${IMAGE}:latest .

if [ "$1" = "--publish" ]
then
  set -x
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
