#!/bin/bash -ex

# Things you might want to adjust:
IMAGE=couchbasebuild/rpm-packager
ROCKY_VERSION=${ROCKY_VERSION:-9}
# You can probably ignore the rest of this

TAG="rocky${ROCKY_VERSION}-$(date +%Y%m%d)"

# Default values
ACTION=--load
case "$(uname -m)" in
  x86_64)
    PLATFORM=linux/amd64
    ;;
  aarch64|arm64)
    PLATFORM=linux/arm64
    ;;
  *)
    echo "Unsupported architecture: $(uname -m)"
    exit 1
    ;;
esac

# Parse command line arguments
for arg in "$@"; do
  case "${arg}" in
    --publish)
      ACTION=--push
      PLATFORM="linux/amd64,linux/arm64"
      ;;
    --arm)
      [ "${PLATFORM}" = "linux/amd64" ] && ACTION=""
      PLATFORM=linux/arm64
      ;;
    --amd)
      [ "${PLATFORM}" = "linux/arm64" ] && ACTION=""
      PLATFORM=linux/amd64
      ;;
    --both)
      PLATFORM="linux/amd64,linux/arm64"
      ;;
    *)
      echo "Invalid flag: ${arg}"
      echo "Usage: $0 [--publish] [--arm|--amd|--both]"
      exit 1
      ;;
  esac
done

docker buildx build ${ACTION} \
  --ulimit nofile=1024 \
  --platform ${PLATFORM} \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:rocky${ROCKY_VERSION}-latest \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg ROCKY_VERSION=${ROCKY_VERSION} \
  .
