#!/bin/bash -ex

# Things you might want to adjust:
IMAGE=couchbasebuild/server-dfs
# You can probably ignore the rest of this

TAG=$(date +%Y%m%d)

. versions


# Default values
ACTION=--load
case "$(uname -m)" in
  x86_64)
    PLATFORM=linux/amd64
    ;;
  aarch64|arm64)
    PLATFORM=linux/arm64
    ;;
  *)
    echo "Unsupported architecture: $(uname -m)"
    exit 1
    ;;
esac

# Parse command line arguments
for arg in "$@"; do
  case "${arg}" in
    --publish)
      ACTION=--push
      PLATFORM="linux/amd64,linux/arm64"
      ;;
    --arm)
      [ "${PLATFORM}" = "linux/amd64" ] && ACTION=""
      PLATFORM=linux/arm64
      ;;
    --amd)
      [ "${PLATFORM}" = "linux/arm64" ] && ACTION=""
      PLATFORM=linux/amd64
      ;;
    --both)
      PLATFORM="linux/amd64,linux/arm64"
      ;;
    *)
      echo "Invalid flag: ${arg}"
      exit 1
      ;;
  esac
done

docker buildx build ${ACTION} \
  --ulimit nofile=1024 \
  --platform ${PLATFORM} \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg CCACHE_VERSION=${CCACHE_VERSION} \
  --build-arg CMAKE_VERSION=${CMAKE_VERSION} \
  --build-arg JQ_VERSION=${JQ_VERSION} \
  --build-arg JDK_VERSION=${JDK_VERSION} \
  --build-arg PATCH_VIA_GERRIT_VERSION=${PATCH_VIA_GERRIT_VERSION} \
  --build-arg RSYNC_VERSION=${RSYNC_VERSION} \
  --build-arg LIBXXHASH_VERSION=${LIBXXHASH_VERSION} \
  --build-arg YQ_VERSION=${YQ_VERSION} \
  .
