#!/bin/sh -ex

# Things you might want to adjust:
IMAGE=couchbasebuild/server-linux-cv

# You can probably ignore the rest of this

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build
cp -a ../../util/hooks/buildx.sh build
cp -a ../cv-hook.sh build
cp ../gitconfig ./build/
cp ../ssh_environment ./build/

. ../versions

TAG=$(date +%Y%m%d)

if [ "$1" = "--publish" ]
then
  ACTION=--push
  BUILDX=buildx
  PLATFORMS="--platform linux/amd64,linux/arm64"
fi

docker ${BUILDX} build --pull ${ACTION} ${PLATFORMS} \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg ASPELL_DICT_VERSION=${ASPELL_DICT_VERSION} \
  --build-arg VALGRIND_VERSION=${VALGRIND_VERSION} \
  --build-arg DOCKER_VERSION=${DOCKER_VERSION} \
  --build-arg JYTHON_VERSION=${JYTHON_VERSION} \
  .
