version: '3.5'

# Suggested deployment command:
#  docker --host build-db-01.build.couchbase.com stack deploy -c builddb_rest.yaml builddb_rest
# All services, networks, etc. will then get an "builddb_rest" prefix,
# eg. "builddb_rest_server"

services:

  server:
    image: couchbasebuild/builddb_rest:20200901
    deploy:
      replicas: 3
    ports:
      - "8000:6543"
    volumes:
      - type: bind
        source: /buildteam/builddb_repos
        target: /var/builddb_repos
    configs:
      - source: builddb_rest_20181219
        target: /etc/builddb_rest.ini
        uid: '1000'
        gid: '1000'
    networks:
      - builddb_rest

configs:
  builddb_rest_20181219:
    file: conf/builddb_rest.ini

networks:
  builddb_rest:
