#!/bin/bash -e
for encoding in none base64
do
    # Get the names of the secrets we want from parameter store
    secrets=$(aws ssm --region us-east-2 describe-parameters --parameter-filters "Key=tag:Consumer,Values=gerrit" "Key=tag:Encoding,Values=${encoding}" | jq -r ".Parameters[].Name")
    target_dir="/home/ec2-user/"
    for secret in ${secrets}
    do
        echo "Reading ${secret}"
        # We're composing filenames from parameters like: gerrit__.ssh__config
        # where each __ is replaced with a / to construct the path.
        #
        # The first component of this string specifies the application, whatever
        # remains as the path.
        #
        # e.g:
        #   gerrit__.ssh__config = [/home/ec2-user/].ssh/config
        secret_path="${target_dir}$(echo ${secret} | sed -e"s/__/\//g;s/^gerrit\///g")"
        mkdir -p $(dirname ${secret_path})
        param=$(aws ssm get-parameter --region us-east-2 --with-decryption --name ${secret} | jq -r ".Parameter.Value")
        case ${encoding} in
        none)
            echo "${param}" > "${secret_path}"
            ;;
        base64)
            echo "${param}" | base64 --decode > "${secret_path}"
            ;;
        esac
    done
    chown -R 1000:1000 /home/ec2-user/.ssh
    chmod 600 /home/ec2-user/.ssh/*
done
