#!/bin/bash -e

TAG=$(date "+%Y%m%d")
IMAGE="couchbasebuild/load-build-database"

rm -rf build
mkdir build
for entry in build_database setup.cfg pyproject.toml; do
    cp -a ../../../build_database/$entry build
done

docker build --no-cache -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
