#!/bin/bash -e

usage() {
    echo "Usage: $(basename $0) -n NAME -x XEN_HOST -p XEN_PASSWORD"
    echo "    [-m MEMORY] [-c CPUS] [-d DISKSPACE]"
    echo "    [-r ROLES] [-e ROLE_ARG=VALUE]"
    echo "    [-s SWARM_MANAGER] [-l SWARM_LABELS]"
    echo "Defaults: memory 20GB; cpus 8; diskpace 200GB; no Swarm"
    exit 1
}


while getopts ":n:x:p:m:c:d:s:l:r:e:" opt; do
    case ${opt} in
        n)
            NAME=${OPTARG}
            ;;
        x)
            XEN_HOST=${OPTARG}
            ;;
        p)
            XEN_PASSWORD=${OPTARG}
            ;;
        m)
            MEMORY=${OPTARG}
            ;;
        m)
            MEMORY=${OPTARG}
            ;;
        c)
            CPUS=${OPTARG}
            ;;
        d)
            DISKSPACE=${OPTARG}
            ;;
        r)
            ROLES=${OPTARG}
            ;;
        e)
            ARGS="-e ${OPTARG} ${ARGS}"
            ;;
        s)
            ARGS="-e swarm_manager=${OPTARG} ${ARGS}"
            ;;
        l)
            ARGS="-e swarm_labels=${OPTARG} ${ARGS}"
            ;;
        \?)
            usage
            ;;
        :)
            echo "-${OPTARG} requires an argument"
            usage
            ;;
    esac
done

[ -z "${NAME}" ] && usage
[ -z "${XEN_HOST}" ] && usage
[ -z "${XEN_PASSWORD}" ] && usage
MEMORY=${MEMORY:-20}
CPUS=${CPUS:-8}
DISKSPACE=${DISKSPACE:-200}

docker run --rm \
    -v $(pwd):/mnt \
    -v $(git rev-parse --show-toplevel)/ansible/common/roles:/rolescommon \
    -v $(git rev-parse --show-toplevel)/ansible/linux/common/roles:/roleslinux \
    couchbasebuild/ansible-playbook:6.2.0 \
    -v -i inventory -l ${XEN_HOST}:newvms playbook.yml \
    -e cmdline_password=${XEN_PASSWORD} \
    -e vm_name=${NAME} -e role_list=${ROLES} \
    -e memory=${MEMORY} -e vcpus=${CPUS} -e disksize=${DISKSPACE} \
    ${ARGS}
