PS1="\[\e[01;32m\]\u@\h \[\e[01;34m\]\W \`if [ \$? != 0 ]; then echo -e '\[\e[01;31m\]:('; fi\` \[\e[01;34m\]$ \[\e[00m\]"

if [ "`id -u`" -eq 0 ]; then
    usercol=";31"
fi
PS1="[\[\e[1$(if [ \"`id -u`\" = \"0\" ]; then echo -e ';31'; else echo -e ';34'; fi)m\]\u\[\e[1;36m\]\[\033[m\]@\[\e[1;36m\]\h\[\033[m\]:\[\e[0m\]\[\e[1;32m\]\W\[\e[0m\]]$ "
