#!/bin/sh -ex

# Things you might want to adjust:
IMAGE=couchbasebuild/server-linux-build

# You can probably ignore the rest of this


export DOCKER_BUILDKIT=1

. ../versions

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

TAG=$(date +%Y%m%d)

if [ "$1" = "--publish" ]
then
  PUSH=--push
fi

docker buildx build --pull ${PUSH} \
  --platform linux/amd64,linux/arm64 \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  --build-arg IMAGEROOT=${IMAGEROOT} \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg ASCIIDOCTOR_VER=${ASCIIDOCTOR} \
  --build-arg AUTOCONF_VER=${AUTOCONF} \
  --build-arg AUTOMAKE_VER=${AUTOMAKE} \
  --build-arg CBDEP_VER=${CBDEP} \
  --build-arg CCACHE_VER=${CCACHE} \
  --build-arg CLANG_VER=${CLANG} \
  --build-arg CMAKE_MAJOR=${CMAKE_MAJOR} \
  --build-arg CMAKE_MINOR=${CMAKE_MINOR} \
  --build-arg CMAKE_PATCH=${CMAKE_PATCH} \
  --build-arg DOCKER_VER=${DOCKER} \
  --build-arg GCC_VER=${GCC} \
  --build-arg GCC_12_VER=${GCC_12} \
  --build-arg GIT_VER=${GIT} \
  --build-arg JNLP_AGENT_VER=${JNLP_AGENT} \
  --build-arg LIBTOOL_VER=${LIBTOOL} \
  --build-arg PATCH_VIA_GERRIT_VER=${PATCH_VIA_GERRIT} \
  --build-arg PYTHON3_MAJOR=${PYTHON3_MAJOR} \
  --build-arg PYTHON3_MINOR=${PYTHON3_MINOR} \
  --build-arg PYTHON3_PATCH=${PYTHON3_PATCH} \
  --build-arg RUBY_MAJOR=${RUBY_MAJOR} \
  --build-arg RUBY_MINOR=${RUBY_MINOR} \
  --build-arg RUBY_PATCH=${RUBY_PATCH} \
  --build-arg RUBY_INSTALL_MAJOR=${RUBY_INSTALL_MAJOR} \
  --build-arg RUBY_INSTALL_MINOR=${RUBY_INSTALL_MINOR} \
  --build-arg RUBY_INSTALL_PATCH=${RUBY_INSTALL_PATCH} \
  --build-arg TINI_VER=${TINI} \
  --build-arg YQ_VER=${YQ} \
  .

# Also ensure the sidecars are updated appropriately
for pkg_type in deb rpm
do
  pushd ${pkg_type}-sidecar
  ./go $1
  popd
done
