#!/bin/sh -e

TAG=`date +%Y%m%d`
IMAGE=couchbasebuild/ubuntu2004-mobile-lite-android

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

if [ "$1" = "--publish" ]
then
  ACTION=--push
else
  ACTION=--load
fi

docker buildx build --pull ${ACTION} \
  --platform linux/amd64 \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  .
