#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-ubuntu18-clang9-build

if [ "$1" = "--publish" ]
then
  ACTION=--push
else
  ACTION=--load
fi

docker buildx build --pull ${ACTION} \
  --platform linux/amd64 \
  --tag ${IMAGE}:${TAG} \
  .
