#!/bin/sh

# Bump this when rebuilding with changes
TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/server-ubuntu12-cv

mkdir -p build
if [ ! -d build/jdk1.8.0_181 ]; then
    curl http://downloads.build.couchbase.com/jdk/jdk-8u181-linux-x64.tar.gz | \
    tar x -C build -z
fi

docker build --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
