- name: Install brew
  block:
  - name: Check if installed (brew)
    stat:
      path: "{{ homebrew_dir }}/bin/brew"
    register: brew_stat

  - debug: msg="Installing homebrew.  This will take a while"
    when: not brew_stat.stat.exists

  - name: install homebrew
    shell: |
      yes| /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    when: not brew_stat.stat.exists

  - name: Add formulae (brew)
    homebrew:
      name: "{{ homebrew_installed_packages }}"
    environment:
      PATH: "{{ homebrew_dir }}/bin:{{ ansible_env.PATH }}"

  # after first installing formulae, /usr/local/zsh gets weird permissions and
  # errors start happening when you run /bin/zsh
  - name: Fix directory permissions
    file:
      path: "{{ homebrew_dir }}/share/zsh"
      state: directory
      recurse: yes
      owner: couchbase
      group: staff
      mode: '0755'
    become: true

  - name: Link libtoolize (brew)
    file:
      src: "{{ homebrew_dir }}/bin/glibtoolize"
      dest: "{{ homebrew_dir }}/bin/libtoolize"
      state: link

  - name: Install gems
    shell: command -v xcode-install || {{ homebrew_dir }}/opt/ruby@{{ ruby_version }}/bin/gem install xcode-install
    become: true
  tags: brew
