#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/sdk-alpine-build

mkdir -p build
INFRADIR=$(git rev-parse --show-toplevel)
cp -a ${INFRADIR}/docker/buildslaves/util/couchbuilder_transition_start.sh build/couchbuilder_start.sh

if [ "$1" = "--publish" ]
then
  ACTION="--push"
else
  ACTION="--load"
fi

docker buildx build --platform linux/amd64 --pull ${ACTION} \
    --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
    --build-arg CACHEBUST=$(date +%Y%m%d-%H%M%S) \
    --build-arg CMAKE_VERSION=3.21.3 \
    --build-arg GRADLE_VERSION=4.10 \
    --build-arg MAVEN_VERSION=3.5.4 \
    --build-arg SWARM_CLIENT_VERSION=3.24 \
    -t ${IMAGE}:${TAG} \
    -t ${IMAGE}:latest \
    .
