version: '3.8'

# Suggested deployment command:
#  docker --host 172.23.107.124 stack deploy --with-registry-auth -c analytics-jenkins-agents.yml analytics
# All services, networks, etc. will then get an "analytics_" prefix,
# eg. "analytics_ubuntu18"

# Default agent configuration. This is written using a YAML anchor so
# it can be substituted into all the agent declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-agent: &default-jenkins-agent
  networks:
    - jenkins
  extra_hosts:
    - "host.docker.internal:host-gateway"
  sysctls:
    net.ipv6.conf.lo.disable_ipv6: 0

  configs:
    - source: jenkins_master_username
      target: /run/secrets/jenkins_master_username
      mode: 0444
    - source: jenkins_master_username
      target: /run/secrets/jenkins_username
      mode: 0444

  secrets:
    - source: analytics_jenkins_ns-buildbot_api_key.20220510
      target: /run/secrets/jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profiledata_ssh_key

services:

  zz-lightweight:
    image: couchbasebuild/zz-lightweight:20260212
    environment:
      - "JENKINS_SLAVE_NAME=zz-analytics-lightweight"
      - "JENKINS_SLAVE_LABELS=zz-lightweight"
      - "JENKINS_SLAVE_EXECUTORS=15"
      - "JENKINS_MASTER=http://analytics.jenkins.couchbase.com/"
      - "JENKINS_TUNNEL=mega4.build.couchbase.com:"
      - "NODE_CLASS=cv zz"
      - "NODE_PRODUCT=couchbase-server"
      - "COUCHBASE_DISABLED_UNIT_TESTS=ALL"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18"
        max_replicas_per_node: 1
      replicas: 1

  linux:
    image: couchbasebuild/analytics-linux-cv:20260818

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/couchbase/jenkins:/home/couchbase/jenkins"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - JENKINS_SLAVE_NAME=analytics
      - "JENKINS_SLAVE_LABELS=analytics server couchsterix-test"
      - JENKINS_MASTER=http://analytics.jenkins.couchbase.com/
      - "JENKINS_TUNNEL=mega4.build.couchbase.com:"
      - NODE_CLASS=cv zz
      - NODE_PRODUCT=couchbase-server
      - COUCHBASE_DISABLED_UNIT_TESTS=ALL
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"

    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18"
        max_replicas_per_node: 1
      replicas: 15
      update_config:
        parallelism: 100

  dfs:
    image: couchbasebuild/analytics-dfs-cv:20260818
    init: true
    environment:
      - "JENKINS_AGENT_NAME=analytics-dfs"
      - "JENKINS_AGENT_LABELS={{.Node.Hostname}} dfs"
      - "JENKINS_URL=http://analytics.jenkins.couchbase.com/"
      - "JENKINS_TUNNEL=mega4.build.couchbase.com:"
      - "CB_ENTRYPOINT_PLUGINS=docker/ensure_docker_group secrets/profiledata jenkins/swarm"
      - "CB_ENTRYPOINT_PLUGINS_EC2=docker/ensure_docker_group secrets/home_mount jenkins/ec2"
      - "CB_ENTRYPOINT_BASE=https://cb-entry.s3.us-west-2.amazonaws.com"
      - "NODE_CLASS=cv-docker"
      - "NODE_PRODUCT=couchbase-server"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    secrets:
      - source: analytics_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_password
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profiledata_ssh_key
    healthcheck:
      test: ["CMD", "/tmp/healthcheck.sh"]
      interval: 30s
      timeout: 90s
      retries: 3
    user: couchbase
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /proc
        target: /opt/rpm-chroot/proc
      - type: bind
        source: /proc
        target: /opt/deb-chroot/proc

    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu24"
        max_replicas_per_node: 1
      replicas: 1
      update_config:
        parallelism: 100
        delay: 0s

secrets:
  analytics_jenkins_ns-buildbot_api_key.20220510:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true
  nsbuildbot-docker-config.json:
    external: true

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

networks:
  jenkins:
    attachable: true
    labels:
      cbas-docker-test: 0
