version: '3.5'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c analytics-jenkins.yaml analytics
# All services, networks, etc. will then get an "analytics_" prefix,
# eg. "analytics_jenkins"

services:

  # analytics.jenkins.couchbase.com
  jenkins:
    image: jenkins/jenkins:2.414.1
    deploy:
      resources:
        limits:
          memory: 7G
        reservations:
          memory: 7G
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"
        - "traefik.http.routers.analytics_jenkins.rule=Host(`analytics.jenkins.couchbase.com`)"
        - "traefik.http.services.analytics_jenkins.loadbalancer.server.port=8080"
    ports:
      - "50000:50000"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /buildteam/jenkins/analytics-jenkins-home
        target: /var/jenkins_home
    networks:
      - jenkins
      - traefik_reverse-proxy

# See http://www.technowise.in/2016/10/fix-no-valid-crumb-was-included-in.html
# and https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Nginx
# for the reason behind -Dhudson.security.csrf.requestfield
    environment:
      - "JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.security.csrf.requestfield=Jenkins-Crumb"
      - "JENKINS_OPTS=--sessionTimeout=1440 --sessionEviction=14400"

networks:
  jenkins:
  traefik_reverse-proxy:
    external: true
