version: '3.8'

# Suggested deployment command:
#  docker --host 172.23.107.124 stack deploy --with-registry-auth -c analytics-jenkins-agents.yml analytics
# All services, networks, etc. will then get an "analytics_" prefix,
# eg. "analytics_ubuntu18"

# Default agent configuration. This is written using a YAML anchor so
# it can be substituted into all the agent declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-agent: &default-jenkins-agent
  networks:
    - jenkins
  extra_hosts:
    - "host.docker.internal:host-gateway"
  sysctls:
    net.ipv6.conf.lo.disable_ipv6: 0

  configs:
    - source: jenkins_master_username
      target: /run/secrets/jenkins_master_username
      mode: 0444

  secrets:
    - source: analytics_jenkins_ns-buildbot_api_key.20220510
      target: /run/secrets/jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync

services:

  zz-lightweight:
    image: couchbasebuild/zz-lightweight:20260114
    environment:
      - "JENKINS_SLAVE_NAME=zz-analytics-lightweight"
      - "JENKINS_SLAVE_LABELS=zz-lightweight"
      - "JENKINS_SLAVE_EXECUTORS=15"
      - "JENKINS_MASTER=http://analytics.jenkins.couchbase.com/"
      - "JENKINS_TUNNEL=mega4.build.couchbase.com:"
      - "NODE_CLASS=cv zz"
      - "NODE_PRODUCT=couchbase-server"
      - "COUCHBASE_DISABLED_UNIT_TESTS=ALL"
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"
    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18"
        max_replicas_per_node: 1
      replicas: 1

  linux:
    image: couchbasebuild/analytics-linux-cv:20260109

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/couchbase/jenkins:/home/couchbase/jenkins"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - JENKINS_SLAVE_NAME=analytics
      - "JENKINS_SLAVE_LABELS=analytics server couchsterix-test"
      - JENKINS_MASTER=http://analytics.jenkins.couchbase.com/
      - "JENKINS_TUNNEL=mega4.build.couchbase.com:"
      - NODE_CLASS=cv zz
      - NODE_PRODUCT=couchbase-server
      - COUCHBASE_DISABLED_UNIT_TESTS=ALL
      - "REPO_URL=https://github.com/couchbasedeps/git-repo"

    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18"
        max_replicas_per_node: 1
      replicas: 15
      update_config:
        parallelism: 100

secrets:
  analytics_jenkins_ns-buildbot_api_key.20220510:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true
  nsbuildbot-docker-config.json:
    external: true

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

networks:
  jenkins:
    attachable: true
    labels:
      cbas-docker-test: 0
