version: "3.8"

# Stack for general-purpose agent capable of running "docker buildx build".

# Shared environment lines
x-jenkins-environment:
  - &jenkins-master "JENKINS_MASTER=http://server.jenkins.couchbase.com/"
  - &node-product "NODE_PRODUCT=couchbase-server"
  - &repo-url "REPO_URL=https://github.com/couchbasedeps/git-repo"

# Shared configs + secrets
x-shared-refs:
  - &cfg-jenkins-master-username
    source: jenkins_master_username
    target: /run/secrets/jenkins_master_username
    mode: 0444
  - &sec-jenkins-master-password
    source: server_jenkins_ns-buildbot_api_key.20220510
    target: /run/secrets/jenkins_master_password
  - &sec-profile-sync
    source: profiledata.ssh_privkey.profile_sync.20200423
    target: /run/secrets/profile_sync

# Shared deploy bits for buildx-family agents; replicas overridden per-service
x-default-buildx-deploy: &default-buildx-deploy
  placement:
    constraints:
      - node.labels.role==docker-buildx
  update_config:
    parallelism: 1000

# Shared volumes for buildx-family agents
x-default-buildx-volumes: &default-buildx-volumes
  - "/var/run/docker.sock:/var/run/docker.sock:rw"
  - "/etc/localtime:/etc/localtime"
  - "/etc/timezone:/etc/timezone"
  - "latestbuilds:/latestbuilds"
  - "releases:/releases"
  - "buildteam:/buildteam"

services:
  buildx:
    # Historically, this was the agent used for
    # couchbase-k8s-microservice builds, so it still has
    # operator-specific Jenkins labels.
    image: couchbasebuild/buildx:20260507
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=buildx"
      - "JENKINS_SLAVE_LABELS=couchbase-k8s-microservices couchbase-operator master buildx"
      - *jenkins-master
      - "NODE_CLASS=build buildx"
      - *node-product
      - *repo-url
    volumes: *default-buildx-volumes
    configs:
      - *cfg-jenkins-master-username
    secrets:
      - *sec-jenkins-master-password
      - *sec-profile-sync
    deploy:
      <<: *default-buildx-deploy
      replicas: 3

  zzz-buildx:
    image: couchbasebuild/zzz-lightweight:20260506
    init: true
    environment:
      - "JENKINS_SLAVE_NAME=zzz-buildx"
      - "JENKINS_SLAVE_LABELS=zzz-buildx"
      - "JENKINS_SLAVE_EXECUTORS=10"
      - *jenkins-master
      - "NODE_CLASS=build buildx"
      - *node-product
      - *repo-url
    volumes: *default-buildx-volumes
    configs:
      - *cfg-jenkins-master-username
    secrets:
      - *sec-jenkins-master-password
      - *sec-profile-sync
    deploy:
      <<: *default-buildx-deploy
      replicas: 1

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

secrets:
  server_jenkins_ns-buildbot_api_key.20220510:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true

volumes:
  workspace:
  latestbuilds:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/builds/latestbuilds"

  releases:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/builds/releases"

  buildteam:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/buildteam"
