#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-centos7-build
. ../versions

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

docker build \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg ASCIIDOCTOR_VER=${ASCIIDOCTOR} \
  --build-arg AUTOCONF_VER=${AUTOCONF} \
  --build-arg AUTOMAKE_VER=${AUTOMAKE} \
  --build-arg CCACHE_VER=${CCACHE} \
  --build-arg CMAKE_MAJOR=${CMAKE_MAJOR} \
  --build-arg CMAKE_MINOR=${CMAKE_MINOR} \
  --build-arg CMAKE_PATCH=${CMAKE_PATCH} \
  --build-arg GCC_VER=${GCC} \
  --build-arg GIT_VER=${GIT} \
  --build-arg JNLP_AGENT_VER=${JNLP_AGENT} \
  --build-arg LIBTOOL_VER=${LIBTOOL} \
  --build-arg PYTHON3_MAJOR=${PYTHON3_MAJOR} \
  --build-arg PYTHON3_MINOR=${PYTHON3_MINOR} \
  --build-arg PYTHON3_PATCH=${PYTHON3_PATCH} \
  --build-arg RUBY_MAJOR=${RUBY_MAJOR} \
  --build-arg RUBY_MINOR=${RUBY_MINOR} \
  --build-arg RUBY_PATCH=${RUBY_PATCH} \
  --build-arg RUBY_INSTALL_MAJOR=${RUBY_INSTALL_MAJOR} \
  --build-arg RUBY_INSTALL_MINOR=${RUBY_INSTALL_MINOR} \
  --build-arg RUBY_INSTALL_PATCH=${RUBY_INSTALL_PATCH} \
  --build-arg TINI_VER=${TINI} \
  -t ${IMAGE}:${TAG} -t ${IMAGE}:latest .
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
