#!/bin/sh -e

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/centos7-sgw-build

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

if [ "$1" = "--publish" ]
then
  ACTION="--push"
else
  ACTION="--load"
fi

docker buildx build ${ACTION} \
    --platform linux/amd64 \
    -t ${IMAGE}:$TAG \
    -t ${IMAGE}:latest \
    .
