#!/bin/bash -e

TAG=$(date "+%Y%m%d")
IMAGE="couchbasebuild/generate_private_repos"

rm -rf build-tools manifest
git clone https://github.com/couchbase/build-tools.git
git clone https://github.com/couchbase/manifest.git

docker build -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
