#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-suse11-build

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
# Note: the gcc build image is in build-infra.
if [ ! -d build/local ]
then
    docker run --rm -v $(pwd)/build:/output \
        couchbasebuild/suse-11-gcc:7.3.0 \
        cp -a /usr/local /output
fi

# The OpenSSL in OpenSUSE 11 is so old that it can't contact some
# websites anymore. So we have to download those files here and
# COPY them into the image. This is annoying because COPY makes a
# new image layer and hence the image will be larger than it needs
# to be.
if [ ! -e build/ccache.tar.bz2 ]
then
    curl -o build/ccache.tar.bz2 \
        https://www.samba.org/ftp/ccache/ccache-3.4.2.tar.bz2
fi
if [ ! -e build/swarm-client-3.17.jar ]
then
    curl -o build/swarm-client-3.17.jar \
        https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.17/swarm-client-3.17.jar
fi

docker build -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
