#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-ubuntu20-build
. ../versions

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/healthcheck.sh build

docker build \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg ASCIIDOCTOR_VER=${ASCIIDOCTOR} \
  --build-arg GCC_VER=${GCC} \
  --build-arg CMAKE_MAJOR=${CMAKE_MAJOR} \
  --build-arg CMAKE_MINOR=${CMAKE_MINOR} \
  --build-arg CMAKE_PATCH=${CMAKE_PATCH} \
  --build-arg JNLP_AGENT_VER=${JNLP_AGENT} \
  --build-arg SWARM_CLIENT_VER=${SWARM_CLIENT} \
  -t ${IMAGE}:${TAG} -t ${IMAGE}:latest .
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
