#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-ubuntu20-build

mkdir -p build
cp ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp ../../util/swarm*.properties build

# Only copy this if it doesn't exist. Prevents re-running steps in
# this Dockerfile. This does mean that if you need to update the
# gcc, you need to manually delete this directory and rebuild.
# Note: the gcc build image is in build-infra.
if [ ! -d build/gcc ]
then
    docker run --rm -v $(pwd)/build:/output \
        couchbasebuild/ubuntu-2004-gcc:7.5.0 \
        cp -a /opt/gcc /output
fi

docker build --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} -t ${IMAGE}:${TAG} -t ${IMAGE}:latest .
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
