#!/bin/sh -e

VERSION=6.1.0

for command in ansible ansible-playbook
do
  IMAGE=couchbasebuild/${command}
  docker build --pull \
    --build-arg ANSIBLE_COMMAND=${command} \
    --build-arg ANSIBLE_VERSION=${VERSION} \
    --tag $IMAGE:$VERSION .
  docker tag $IMAGE:$VERSION $IMAGE:latest
  if [ "$1" = "--publish" ]
  then
    docker push $IMAGE:$VERSION
    docker push $IMAGE:latest
  fi
done
