#!/bin/sh -e

TAG=2.4.1

for command in ansible ansible-playbook
do
  IMAGE=couchbasebuild/${command}
  docker build --build-arg ANSIBLE_COMMAND=${command} --tag $IMAGE:$TAG .
  docker tag $IMAGE:$TAG $IMAGE:latest
  if [ "$1" = "--publish" ]
  then
    docker push $IMAGE:$TAG
    docker push $IMAGE:latest
  fi
done

