#!/bin/sh -e

VERSION=2.5.0

for command in ansible ansible-playbook
do
  IMAGE=couchbasebuild/${command}
  docker build \
    --build-arg ANSIBLE_COMMAND=${command} \
    --build-arg ANSIBLE_VERSION=${VERSION} \
    --tag $IMAGE:$VERSION .
  docker tag $IMAGE:$VERSION $IMAGE:latest
  if [ "$1" = "--publish" ]
  then
    docker push $IMAGE:$VERSION
    docker push $IMAGE:latest
  fi
done

