variable "prefix" {}
variable "vpc_id" {}
variable "private_subnets_cidr_blocks" {}
variable "private_subnets" {}
variable "efs_file_system" {}
variable "proget_ami" {}
variable "proget_instance_type" {}
variable "stopped" {}
variable "region" {}
variable "dns_namespace" {}
variable "efs_security_group" {}
variable "bastion_security_group" {}
