#!/bin/sh

TAG=$(date "+%Y%m%d")
IMAGE=couchbasebuild/analytics-ubuntu18-cv

cp ../../util/healthcheck.sh .

docker build \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  -t ${IMAGE}:${TAG} \
  -t ${IMAGE}:latest \
  .

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
