#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/python-alpine-build

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build

docker build . \
    -t ${IMAGE}:${TAG} \
    -t ${IMAGE}:latest \
    --build-arg SWARM_CLIENT_VERSION=3.24

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
