#!/bin/bash -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/zzz-lightweight
. ../versions

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build

docker build --pull \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  -t ${IMAGE}:${TAG} \
  -t ${IMAGE}:latest \
  .
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
