#!/bin/bash -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/zz-lightweight
. ../versions

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build
cp -a ../../util/hooks/buildx.sh build

if [ "$1" = "--publish" ]
then
  ACTION="--push"
else
  ACTION="--load"
fi

docker buildx build --pull ${ACTION} \
  --platform linux/amd64 \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  -t ${IMAGE}:${TAG} \
  -t ${IMAGE}:latest \
  .
