#!/bin/bash

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/swarm-launcher

docker build -t ${IMAGE}:${TAG} -t ${IMAGE}:latest .
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi

