#!/bin/sh -ex

export BINUTILS_VER=${BINUTILS_VER:-2.41}
export CLANG_VER=${CLANG_VER:-18.1.8}
export GCC_VER=${GCC_VER:-13.2.0}
export GCC_TAG=${GCC_TAG:-20241203}
export DOCKER_BUILDKIT=1

IMAGE_NAME=couchbasebuild/single-clang

if [ "$1" = "--publish" ]
then
  BUILDER=buildx
  PLATFORMS="--platform linux/amd64,linux/arm64"
  PUSH=--push
fi

docker ${BUILDER} build \
  -f Dockerfile \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  --build-arg BINUTILS_VER=${BINUTILS_VER} \
  --build-arg CLANG_VER=${CLANG_VER} \
  --build-arg GCC_CONTAINER=couchbasebuild/single-gcc:${GCC_VER}-${GCC_TAG} \
  --build-arg GCC_VER=${GCC_VER} \
  ${PLATFORMS} \
  --pull ${PUSH} \
  --tag ${IMAGE_NAME}:${CLANG_VER}-$(date +%Y%m%d) \
  .
