#!/bin/bash -e

GCC_VER=10.2.0
IMAGE=couchbasebuild/ubuntu-20-gcc

docker build \
    --build-arg GCC_VER=${GCC_VER} \
    -t ${IMAGE}:${GCC_VER} .

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${GCC_VER}
fi
