#!/bin/bash

docker run --rm -it -v `pwd`:/mnt \
-v /home/couchbase/jenkinsdocker-ssh:/home/couchbase/jenkinsdocker-ssh \
couchbasebuild/ansible-playbook -v -i inventory --forks 30 \
restart_cv_dockerslaves.yml $@

