#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/buildx

mkdir -p build

cp ../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp ../util/hooks/buildx.sh build/buildx.sh
cp ../util/swarm*.properties build

docker build --pull -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
