#!/bin/sh -ex

TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-debian10-build
GCC_VER=10.2.0

mkdir -p build
cp -a ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ../../util/swarm*.properties build

docker build \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  --build-arg GCC_VER=${GCC_VER} \
  -t ${IMAGE}:${TAG} -t ${IMAGE}:latest .
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
