#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/sdk-centos7-signing

mkdir -p build
INFRADIR=$(git rev-parse --show-toplevel)
cp -a ${INFRADIR}/docker/buildslaves/util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a ${INFRADIR}/docker/buildslaves/util/healthcheck.sh build/healthcheck.sh

if [ "$1" = "--publish" ]
then
  ACTION="--push"
else
  ACTION="--load"
fi

docker buildx build --platform linux/amd64 --pull ${ACTION} \
    --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
    --build-arg CACHEBUST=$(date +%Y%m%d-%H%M%S) \
    -t ${IMAGE}:${TAG} \
    -t ${IMAGE}:latest \
    .
