#!/bin/bash -e

while [ ! -z "$1" ]; do
  if [[ "$1" == "--change-url" ]]; then
    change_url=$2
  fi
  if [[ "$1" == "--commit" ]]; then
    commit_summary=$(git log -1 --pretty=format:"%s" --shortstat $2 |head -1)
  fi
  if [[ "$1" == "--project" ]]; then
    project_name=$2
  fi
  if [[ "$1" == "--branch" ]]; then
    branch_name=$2
  fi
  shift 2
done

if [[ -n ${change_url} && -n ${commit_summary} ]]; then
  python3 ${GERRIT_SITE}/hooks/jira_hook.py -u "${change_url}" -c "${commit_summary}" -e "change-restored" -p "${project_name}" -b "${branch_name}"
fi
