#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/ubuntu-2004-operator-build
GOVERSION=1.13.3

mkdir -p build

cp ../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp ../util/swarm*.properties build

docker build --build-arg GOVERSION=${GOVERSION} -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
