#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/sdk-mock

if [ "$1" = "--publish" ]
then
  ACTION=--push
else
  ACTION=--load
fi

docker buildx build --pull ${ACTION} \
  --platform linux/amd64 \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  --build-arg CONTAINER_TAG_ARG=${IMAGE}:${TAG} \
  .
