#!/bin/bash -ex

# Things you might want to adjust:
IMAGE=couchbasebuild/server-rpm-sidecar

# You can probably ignore the rest of this

TAG=$(date +%Y%m%d)
if [ "$1" = "--publish" ]; then
  PUSH=--push
fi

docker buildx build --pull $PUSH \
  --tag ${IMAGE}:${TAG} \
  --tag ${IMAGE}:latest \
  --platform linux/amd64,linux/arm64 \
  .
