    <com.cloudbees.jenkins.plugins.amazonecs.ECSCloud plugin="amazon-ecs@1.37">
      <name>${cloud_name}</name>
      <templates>
        <!-- ubuntu:18 -->
        <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate>
          <templateName>ubuntu18_4CPU_8GB</templateName>
          <label>ubuntu</label>
          <taskDefinitionOverride>${task_prefix}-WORKER-analytics-build-ubuntu18</taskDefinitionOverride>
          <defaultCapacityProvider>true</defaultCapacityProvider>
          <remoteFSRoot>/home/couchbase/jenkins</remoteFSRoot>
          <subnets>${subnets}</subnets>
          <securityGroups>${security_groups}</securityGroups>
          <defaultCapacityProvider>true</defaultCapacityProvider>
          <assignPublicIp>false</assignPublicIp>
          <taskrole></taskrole>
          <executionRole>${execution_role}</executionRole>
          <launchType>EC2</launchType>
          <networkMode>bridge</networkMode>
          <privileged>false</privileged>
          <uniqueRemoteFSRoot>false</uniqueRemoteFSRoot>
          <platformVersion>1.4.0</platformVersion>
          <logDriver>awslogs</logDriver>
          <logDriverOptions>
            <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
              <name>awslogs-group</name>
              <value>${cloudwatch_log_group}</value>
            </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
            <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
              <name>awslogs-region</name>
              <value>${region}</value>
            </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
            <com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
              <name>awslogs-stream-prefix</name>
              <value>${cloudwatch_log_prefix}</value>
            </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate_-LogDriverOption>
          </logDriverOptions>
        </com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate>
      </templates>
      <credentialsId></credentialsId>
      <cluster>${cluster_arn}</cluster>
      <regionName>${region}</regionName>
      <tunnel>${jenkins_tunnel}</tunnel>
      <jenkinsUrl>${jenkins_url}</jenkinsUrl>
      <retainAgents>false</retainAgents>
      <retentionTimeout>0</retentionTimeout>
      <slaveTimeoutInSeconds>0</slaveTimeoutInSeconds>
      <taskPollingIntervalInSeconds>0</taskPollingIntervalInSeconds>
      <maxCpu>0</maxCpu>
      <maxMemory>0</maxMemory>
      <maxMemoryReservation>0</maxMemoryReservation>
    </com.cloudbees.jenkins.plugins.amazonecs.ECSCloud>
