#!/bin/bash -e

TAG=$(date "+%Y%m%d")
IMAGE="couchbasebuild/convert_license_text"

docker build -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest

if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:${TAG}
  docker push ${IMAGE}:latest
fi
