#!/bin/bash -ex

# Things you might want to adjust:
IMAGE_NAME=couchbasebuild/dfs-clang
# You can probably ignore the rest of this

TAG=$(date +%Y%m%d)
. ./versions

# Default values
ACTION=--load
case "$(uname -m)" in
  x86_64)
    PLATFORM=linux/amd64
    ;;
  aarch64|arm64)
    PLATFORM=linux/arm64
    ;;
  *)
    echo "Unsupported architecture: $(uname -m)"
    exit 1
    ;;
esac

# Parse command line arguments
for arg in "$@"; do
  case "${arg}" in
    --publish)
      ACTION=--push
      PLATFORM="linux/amd64,linux/arm64"
      ;;
    --arm)
      [ "${PLATFORM}" = "linux/amd64" ] && ACTION=""
      PLATFORM=linux/arm64
      ;;
    --amd)
      [ "${PLATFORM}" = "linux/arm64" ] && ACTION=""
      PLATFORM=linux/amd64
      ;;
    --both)
      PLATFORM="linux/amd64,linux/arm64"
      ;;
    *)
      echo "Invalid flag: ${arg}"
      exit 1
      ;;
  esac
done

build_clang() {
  local clang_version=$1
  local gcc_version=$2
  docker buildx build ${ACTION} --pull \
    --ulimit nofile=1024 \
    --platform ${PLATFORM} \
    --tag ${IMAGE_NAME}:${clang_version}-${TAG} \
    --build-arg CLANG_VERSION=${clang_version} \
    --build-arg GCC_VERSION=${gcc_version} \
    .
}

build_clang "${CLANG_18_VERSION}" "${CLANG_18_GCC_VERSION}"
build_clang "${CLANG_19_VERSION}" "${CLANG_19_GCC_VERSION}"
