#!/bin/sh -ex

# Bump this when rebuilding with changes
TAG=$(date +%Y%m%d)
IMAGE=couchbasebuild/server-amzn2-build

mkdir -p build
cp -a -u ../../util/couchbuilder_transition_start.sh build/couchbuilder_start.sh
cp -a  ../../util/swarm*.properties build

docker build -t ${IMAGE}:${TAG} .
docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
if [ "$1" = "--publish" ]
then
  docker push ${IMAGE}:$TAG
  docker push ${IMAGE}:latest
fi
