version: "3.8"

# Suggested deployment command:
#   docker -H mega4.build.couchbase.com stack deploy --with-registry-auth -c mobile.yml mobile
# All services, networks, etc. will then get an "mobile_" prefix,
# eg. "mobile_zz-lightweight"
#

services:
  zz-lightweight:
    image: couchbasebuild/zz-lightweight:20220708
    environment:
      - "JENKINS_SLAVE_NAME=zz-lightweight"
      - "JENKINS_SLAVE_LABELS=zz-lightweight"
      - "JENKINS_MASTER=http://mobile.jenkins.couchbase.com/"
      - "JENKINS_SLAVE_EXECUTORS=10"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=mobile"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
      - "latestbuilds:/latestbuilds"
      - "releases:/releases"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: mobile_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
        mode: 0444
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
    deploy:
      placement:
        constraints:
          - node.labels.role==build
      update_config:
        parallelism: 1000
    networks:
      - jenkins
      - nfs

  lite-android-ubuntu18:
    image: couchbasebuild/ubuntu1804-mobile-lite-android:20230811
    init: true
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=lite-android-ubuntu18"
      - "JENKINS_SLAVE_LABELS=android cobalt mobile-lite-android"
      - "JENKINS_MASTER=http://mobile.jenkins.couchbase.com/"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=mobile"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: mobile_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
        mode: 0444
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
    deploy:
      placement:
        constraints:
          - node.labels.role==build
      replicas: 3
      update_config:
        parallelism: 1000
    networks:
      - jenkins

  sgw-centos7:
    image: couchbasebuild/centos7-sgw-build:20230414
    init: true
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=sgw-centos7"
      - "JENKINS_SLAVE_LABELS=centos7 mobile mobile-sgw-centos7 sgw"
      - "JENKINS_MASTER=http://mobile.jenkins.couchbase.com/"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=mobile"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: mobile_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
        mode: 0444
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
    deploy:
      placement:
        constraints:
          - node.labels.role==build
      replicas: 1
      update_config:
        parallelism: 1000
    networks:
      - jenkins

  sgw-ubuntu18:
    image: couchbasebuild/ubuntu1804-sgw-build:20230621
    init: true
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=sgw-ubuntu18"
      - "JENKINS_SLAVE_LABELS=ubuntu18 mobile mobile-sgw-ubuntu18 sgw"
      - "JENKINS_MASTER=http://mobile.jenkins.couchbase.com/"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=mobile"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: mobile_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
        mode: 0444
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
    deploy:
      placement:
        constraints:
          - node.labels.role==build
      replicas: 1
      update_config:
        parallelism: 1000
    networks:
      - jenkins

  litecore-centos73:
    image: couchbasebuild/centos-73-litecore-build:20230811
    init: true
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=litecore-centos73"
      - "JENKINS_SLAVE_LABELS=cbl-java cbl-log cblite centos73 litecore"
      - "JENKINS_MASTER=http://mobile.jenkins.couchbase.com/"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: mobile_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
        mode: 0444
    deploy:
      placement:
        constraints:
          - node.labels.role==build
      replicas: 1
      update_config:
        parallelism: 1000
    networks:
      - jenkins

  litec-the-ark:
    image: couchbasebuild/litec-the-ark:20230113
    init: true
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=mobile-litec-the-ark"
      - "JENKINS_SLAVE_LABELS=litec litec-the-ark"
      - "JENKINS_MASTER=http://mobile.jenkins.couchbase.com/"
      - "JENKINS_SLAVE_EXECUTORS=3"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=mobile"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: mobile_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
        mode: 0444
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
    deploy:
      placement:
        constraints:
          - node.labels.role==build
      replicas: 1
      update_config:
        parallelism: 1000
    networks:
      - jenkins

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

secrets:
  mobile_jenkins_ns-buildbot_api_key.20220510:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true

networks:
  jenkins:
  nfs:
   driver: overlay
   attachable: true

volumes:
   latestbuilds:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/builds/latestbuilds"

   releases:
    driver: local
    driver_opts:
        type: "nfs"
        o: "addr=cnt-s231.sc.couchbase.com"
        device: ":/data/builds/releases"
